import { buildJobJsonLd } from '../../lib/seo/jobJsonLd'

describe('buildJobJsonLd', () => {
  it('does not invent validThrough and preserves cleaned HTML descriptions', () => {
    const jsonLd = buildJobJsonLd({
      id: 'ats:test:1',
      title: 'Senior Software Engineer',
      company: 'Acme',
      companyLogo: null,
      locationRaw: 'New York, US',
      city: 'New York',
      citySlug: 'new-york',
      countryCode: 'US',
      remote: false,
      remoteRegion: null,
      remoteMode: 'onsite',
      salaryRaw: null,
      descriptionHtml:
        '<script>alert(1)</script><p>Build platform systems.</p><ul><li>Own backend services.</li></ul>',
      salaryMin: null,
      salaryMax: null,
      salaryCurrency: 'USD',
      salaryPeriod: 'year',
      minAnnual: BigInt(180000),
      maxAnnual: BigInt(220000),
      currency: 'USD',
      isHighSalary: true,
      isHundredKLocal: true,
      isHighSalaryLocal: true,
      type: 'Full-time',
      source: 'greenhouse',
      applyUrl: 'https://jobs.example.com/apply',
      url: 'https://jobs.example.com/role',
      roleSlug: 'software-engineer',
      skillsJson: null,
      requirementsJson: null,
      benefitsJson: null,
      externalId: '1',
      isExpired: false,
      lastSeenAt: new Date('2026-03-20T00:00:00.000Z'),
      postedAt: new Date('2026-03-15T00:00:00.000Z'),
      createdAt: new Date('2026-03-15T00:00:00.000Z'),
      updatedAt: new Date('2026-03-20T00:00:00.000Z'),
      companyId: null,
      locationId: null,
      dedupeKey: null,
      sourcePriority: 20,
      isUnverifiedBoardJob: false,
      experienceLevel: 'senior',
      employmentType: 'full-time',
      workArrangement: null,
      visaSponsorship: false,
      techStack: null,
      industry: null,
      stateCode: 'NY',
      shortId: null,
      aiSummaryJson: null,
      aiSnippet: null,
      aiOneLiner: null,
      aiEnrichedAt: null,
      locationsJson: null,
      primaryLocation: null,
      aiBenefits: null,
      aiRequirements: null,
      aiWhyHighPay: null,
      aiModel: null,
      aiVersion: null,
      aiQualityScore: null,
      lastAiEnrichedAt: null,
      salaryConfidence: 90,
      salaryValidated: true,
      salarySource: 'ats',
      salaryParseReason: null,
      salaryNormalizedAt: null,
      salaryRejectedAt: null,
      salaryRejectedReason: null,
      needsReview: false,
      workArrangementNormalized: null,
      companyRef: {
        id: 'company-1',
        name: 'Acme',
        slug: 'acme',
        website: 'https://acme.com',
        logoUrl: 'https://acme.com/logo.png',
        description: null,
        linkedinUrl: null,
        sizeBucket: null,
        tagsJson: null,
        fundingSummary: null,
        industry: null,
        atsProvider: null,
        atsUrl: null,
        atsSlug: null,
        lastScrapedAt: null,
        scrapeStatus: null,
        scrapeError: null,
        jobCount: 0,
        totalJobCount: null,
        lastJobCountSyncAt: null,
        countryCode: 'US',
        headquarters: null,
        employeeCount: null,
        fundingStage: null,
        foundedYear: null,
        createdAt: new Date('2026-01-01T00:00:00.000Z'),
        updatedAt: new Date('2026-03-20T00:00:00.000Z'),
      },
    } as any)

    expect(jsonLd['@type']).toBe('JobPosting')
    expect(jsonLd.validThrough).toBeUndefined()
    expect(jsonLd.description).toContain('<p>Build platform systems.</p>')
    expect(jsonLd.description).toContain('<li>Own backend services.</li>')
    expect(jsonLd.description).not.toContain('<script>')
    expect(jsonLd.employmentType).toBe('FULL_TIME')
    expect(jsonLd.jobLocation.address.addressCountry).toBe('US')
  })

  it('marks fully remote roles with TELECOMMUTE and applicant location requirements', () => {
    const jsonLd = buildJobJsonLd({
      id: 'ats:test:2',
      title: 'Remote Product Manager',
      company: 'Acme',
      companyLogo: null,
      locationRaw: null,
      city: null,
      citySlug: null,
      countryCode: 'CA',
      remote: true,
      remoteRegion: null,
      remoteMode: 'remote',
      salaryRaw: null,
      descriptionHtml: '<p>Lead distributed product execution.</p>',
      salaryMin: null,
      salaryMax: null,
      salaryCurrency: null,
      salaryPeriod: null,
      minAnnual: null,
      maxAnnual: null,
      currency: null,
      isHighSalary: false,
      isHundredKLocal: false,
      isHighSalaryLocal: false,
      type: null,
      source: 'greenhouse',
      applyUrl: null,
      url: null,
      roleSlug: 'product-manager',
      skillsJson: null,
      requirementsJson: null,
      benefitsJson: null,
      externalId: '2',
      isExpired: false,
      lastSeenAt: null,
      postedAt: new Date('2026-03-15T00:00:00.000Z'),
      createdAt: new Date('2026-03-15T00:00:00.000Z'),
      updatedAt: new Date('2026-03-20T00:00:00.000Z'),
      companyId: null,
      locationId: null,
      dedupeKey: null,
      sourcePriority: 20,
      isUnverifiedBoardJob: false,
      experienceLevel: null,
      employmentType: null,
      workArrangement: null,
      visaSponsorship: false,
      techStack: null,
      industry: null,
      stateCode: null,
      shortId: null,
      aiSummaryJson: null,
      aiSnippet: null,
      aiOneLiner: null,
      aiEnrichedAt: null,
      locationsJson: null,
      primaryLocation: null,
      aiBenefits: null,
      aiRequirements: null,
      aiWhyHighPay: null,
      aiModel: null,
      aiVersion: null,
      aiQualityScore: null,
      lastAiEnrichedAt: null,
      salaryConfidence: 0,
      salaryValidated: false,
      salarySource: null,
      salaryParseReason: null,
      salaryNormalizedAt: null,
      salaryRejectedAt: null,
      salaryRejectedReason: null,
      needsReview: false,
      workArrangementNormalized: null,
      companyRef: null,
    } as any)

    expect(jsonLd.jobLocationType).toBe('TELECOMMUTE')
    expect(jsonLd.jobLocation).toBeUndefined()
    expect(jsonLd.applicantLocationRequirements).toEqual({
      '@type': 'Country',
      name: 'Canada',
    })
  })

  it('infers applicant location requirements from remote location text', () => {
    const jsonLd = buildJobJsonLd({
      id: 'ats:test:3',
      title: 'Remote Data Engineer',
      company: 'Acme',
      companyLogo: null,
      locationRaw: 'Remote (US)',
      city: null,
      citySlug: null,
      countryCode: null,
      remote: true,
      remoteRegion: null,
      remoteMode: 'remote',
      salaryRaw: null,
      descriptionHtml: '<p>Build data platforms remotely.</p>',
      salaryMin: null,
      salaryMax: null,
      salaryCurrency: null,
      salaryPeriod: null,
      minAnnual: null,
      maxAnnual: null,
      currency: null,
      isHighSalary: false,
      isHundredKLocal: false,
      isHighSalaryLocal: false,
      type: null,
      source: 'greenhouse',
      applyUrl: null,
      url: null,
      roleSlug: 'data-engineer',
      skillsJson: null,
      requirementsJson: null,
      benefitsJson: null,
      externalId: '3',
      isExpired: false,
      lastSeenAt: null,
      postedAt: new Date('2026-03-15T00:00:00.000Z'),
      createdAt: new Date('2026-03-15T00:00:00.000Z'),
      updatedAt: new Date('2026-03-20T00:00:00.000Z'),
      companyId: null,
      locationId: null,
      dedupeKey: null,
      sourcePriority: 20,
      isUnverifiedBoardJob: false,
      experienceLevel: null,
      employmentType: null,
      workArrangement: null,
      visaSponsorship: false,
      techStack: null,
      industry: null,
      stateCode: null,
      shortId: null,
      aiSummaryJson: null,
      aiSnippet: null,
      aiOneLiner: null,
      aiEnrichedAt: null,
      locationsJson: null,
      primaryLocation: null,
      aiBenefits: null,
      aiRequirements: null,
      aiWhyHighPay: null,
      aiModel: null,
      aiVersion: null,
      aiQualityScore: null,
      lastAiEnrichedAt: null,
      salaryConfidence: 0,
      salaryValidated: false,
      salarySource: null,
      salaryParseReason: null,
      salaryNormalizedAt: null,
      salaryRejectedAt: null,
      salaryRejectedReason: null,
      needsReview: false,
      workArrangementNormalized: null,
      companyRef: null,
    } as any)

    expect(jsonLd.jobLocationType).toBe('TELECOMMUTE')
    expect(jsonLd.applicantLocationRequirements).toEqual({
      '@type': 'Country',
      name: 'United States',
    })
    expect(jsonLd.jobLocation).toBeUndefined()
  })

  it('avoids emitting TELECOMMUTE when remote geography is unknown', () => {
    const jsonLd = buildJobJsonLd({
      id: 'ats:test:4',
      title: 'Remote Platform Engineer',
      company: 'Acme',
      companyLogo: null,
      locationRaw: 'Remote',
      city: null,
      citySlug: null,
      countryCode: null,
      remote: true,
      remoteRegion: null,
      remoteMode: 'remote',
      salaryRaw: null,
      descriptionHtml: '<p>Operate platform systems remotely.</p>',
      salaryMin: null,
      salaryMax: null,
      salaryCurrency: null,
      salaryPeriod: null,
      minAnnual: null,
      maxAnnual: null,
      currency: null,
      isHighSalary: false,
      isHundredKLocal: false,
      isHighSalaryLocal: false,
      type: null,
      source: 'greenhouse',
      applyUrl: null,
      url: null,
      roleSlug: 'platform',
      skillsJson: null,
      requirementsJson: null,
      benefitsJson: null,
      externalId: '4',
      isExpired: false,
      lastSeenAt: null,
      postedAt: new Date('2026-03-15T00:00:00.000Z'),
      createdAt: new Date('2026-03-15T00:00:00.000Z'),
      updatedAt: new Date('2026-03-20T00:00:00.000Z'),
      companyId: null,
      locationId: null,
      dedupeKey: null,
      sourcePriority: 20,
      isUnverifiedBoardJob: false,
      experienceLevel: null,
      employmentType: null,
      workArrangement: null,
      visaSponsorship: false,
      techStack: null,
      industry: null,
      stateCode: null,
      shortId: null,
      aiSummaryJson: null,
      aiSnippet: null,
      aiOneLiner: null,
      aiEnrichedAt: null,
      locationsJson: null,
      primaryLocation: null,
      aiBenefits: null,
      aiRequirements: null,
      aiWhyHighPay: null,
      aiModel: null,
      aiVersion: null,
      aiQualityScore: null,
      lastAiEnrichedAt: null,
      salaryConfidence: 0,
      salaryValidated: false,
      salarySource: null,
      salaryParseReason: null,
      salaryNormalizedAt: null,
      salaryRejectedAt: null,
      salaryRejectedReason: null,
      needsReview: false,
      workArrangementNormalized: null,
      companyRef: null,
    } as any)

    expect(jsonLd.jobLocationType).toBeUndefined()
    expect(jsonLd.applicantLocationRequirements).toBeUndefined()
    expect(jsonLd.jobLocation).toBeUndefined()
  })
})
