// Shared pSEO target lists for states, skills, industries, and cities.

export type StateTarget = { slug: string; code: string; name: string }
export type SkillTarget = { slug: string; label: string }
export type IndustryTarget = { slug: string; label: string }
export type CityTarget = { slug: string; label: string; countryCode?: string }

export const STATE_TARGETS: StateTarget[] = [
  { slug: 'alabama', code: 'AL', name: 'Alabama' },
  { slug: 'alaska', code: 'AK', name: 'Alaska' },
  { slug: 'arizona', code: 'AZ', name: 'Arizona' },
  { slug: 'arkansas', code: 'AR', name: 'Arkansas' },
  { slug: 'california', code: 'CA', name: 'California' },
  { slug: 'colorado', code: 'CO', name: 'Colorado' },
  { slug: 'connecticut', code: 'CT', name: 'Connecticut' },
  { slug: 'delaware', code: 'DE', name: 'Delaware' },
  { slug: 'florida', code: 'FL', name: 'Florida' },
  { slug: 'georgia', code: 'GA', name: 'Georgia' },
  { slug: 'hawaii', code: 'HI', name: 'Hawaii' },
  { slug: 'idaho', code: 'ID', name: 'Idaho' },
  { slug: 'illinois', code: 'IL', name: 'Illinois' },
  { slug: 'indiana', code: 'IN', name: 'Indiana' },
  { slug: 'iowa', code: 'IA', name: 'Iowa' },
  { slug: 'kansas', code: 'KS', name: 'Kansas' },
  { slug: 'kentucky', code: 'KY', name: 'Kentucky' },
  { slug: 'louisiana', code: 'LA', name: 'Louisiana' },
  { slug: 'maine', code: 'ME', name: 'Maine' },
  { slug: 'maryland', code: 'MD', name: 'Maryland' },
  { slug: 'massachusetts', code: 'MA', name: 'Massachusetts' },
  { slug: 'michigan', code: 'MI', name: 'Michigan' },
  { slug: 'minnesota', code: 'MN', name: 'Minnesota' },
  { slug: 'mississippi', code: 'MS', name: 'Mississippi' },
  { slug: 'missouri', code: 'MO', name: 'Missouri' },
  { slug: 'montana', code: 'MT', name: 'Montana' },
  { slug: 'nebraska', code: 'NE', name: 'Nebraska' },
  { slug: 'nevada', code: 'NV', name: 'Nevada' },
  { slug: 'new-hampshire', code: 'NH', name: 'New Hampshire' },
  { slug: 'new-jersey', code: 'NJ', name: 'New Jersey' },
  { slug: 'new-mexico', code: 'NM', name: 'New Mexico' },
  { slug: 'new-york', code: 'NY', name: 'New York' },
  { slug: 'north-carolina', code: 'NC', name: 'North Carolina' },
  { slug: 'north-dakota', code: 'ND', name: 'North Dakota' },
  { slug: 'ohio', code: 'OH', name: 'Ohio' },
  { slug: 'oklahoma', code: 'OK', name: 'Oklahoma' },
  { slug: 'oregon', code: 'OR', name: 'Oregon' },
  { slug: 'pennsylvania', code: 'PA', name: 'Pennsylvania' },
  { slug: 'rhode-island', code: 'RI', name: 'Rhode Island' },
  { slug: 'south-carolina', code: 'SC', name: 'South Carolina' },
  { slug: 'south-dakota', code: 'SD', name: 'South Dakota' },
  { slug: 'tennessee', code: 'TN', name: 'Tennessee' },
  { slug: 'texas', code: 'TX', name: 'Texas' },
  { slug: 'utah', code: 'UT', name: 'Utah' },
  { slug: 'vermont', code: 'VT', name: 'Vermont' },
  { slug: 'virginia', code: 'VA', name: 'Virginia' },
  { slug: 'washington', code: 'WA', name: 'Washington' },
  { slug: 'west-virginia', code: 'WV', name: 'West Virginia' },
  { slug: 'wisconsin', code: 'WI', name: 'Wisconsin' },
  { slug: 'wyoming', code: 'WY', name: 'Wyoming' },
]

export const SKILL_TARGETS: SkillTarget[] = [
  { slug: 'python', label: 'Python' },
  { slug: 'javascript', label: 'JavaScript' },
  { slug: 'typescript', label: 'TypeScript' },
  { slug: 'react', label: 'React' },
  { slug: 'nextjs', label: 'Next.js' },
  { slug: 'node-js', label: 'Node.js' },
  { slug: 'aws', label: 'AWS' },
  { slug: 'kubernetes', label: 'Kubernetes' },
  { slug: 'docker', label: 'Docker' },
  { slug: 'terraform', label: 'Terraform' },
  { slug: 'golang', label: 'Golang' },
  { slug: 'java', label: 'Java' },
  { slug: 'c-plus-plus', label: 'C++' },
  { slug: 'rust', label: 'Rust' },
  { slug: 'ruby', label: 'Ruby' },
  { slug: 'php', label: 'PHP' },
  { slug: 'sql', label: 'SQL' },
  { slug: 'postgresql', label: 'PostgreSQL' },
  { slug: 'mongodb', label: 'MongoDB' },
  { slug: 'redis', label: 'Redis' },
  { slug: 'graphql', label: 'GraphQL' },
  { slug: 'angular', label: 'Angular' },
  { slug: 'vue', label: 'Vue.js' },
  { slug: 'swift', label: 'Swift' },
  { slug: 'kotlin', label: 'Kotlin' },
  { slug: 'flutter', label: 'Flutter' },
  { slug: 'django', label: 'Django' },
  { slug: 'rails', label: 'Rails' },
  { slug: 'spring', label: 'Spring' },
  { slug: 'machine-learning', label: 'Machine Learning' },
]

export const INDUSTRY_TARGETS: IndustryTarget[] = [
  { slug: 'fintech', label: 'Fintech' },
  { slug: 'ai-ml', label: 'AI / ML' },
  { slug: 'saas', label: 'SaaS' },
  { slug: 'crypto', label: 'Crypto' },
  { slug: 'healthcare-tech', label: 'Healthcare Tech' },
  { slug: 'cybersecurity', label: 'Cybersecurity' },
  { slug: 'edtech', label: 'EdTech' },
  { slug: 'climate-tech', label: 'Climate Tech' },
  { slug: 'gaming', label: 'Gaming' },
  { slug: 'ecommerce', label: 'Ecommerce' },
]

export const CITY_TARGETS: CityTarget[] = [
  // US — Tier 1 tech hubs
  { slug: 'san-francisco', label: 'San Francisco', countryCode: 'US' },
  { slug: 'new-york', label: 'New York', countryCode: 'US' },
  { slug: 'seattle', label: 'Seattle', countryCode: 'US' },
  { slug: 'austin', label: 'Austin', countryCode: 'US' },
  { slug: 'boston', label: 'Boston', countryCode: 'US' },
  { slug: 'los-angeles', label: 'Los Angeles', countryCode: 'US' },
  { slug: 'denver', label: 'Denver', countryCode: 'US' },
  { slug: 'chicago', label: 'Chicago', countryCode: 'US' },
  { slug: 'miami', label: 'Miami', countryCode: 'US' },
  { slug: 'dallas', label: 'Dallas', countryCode: 'US' },
  { slug: 'portland', label: 'Portland', countryCode: 'US' },
  { slug: 'san-diego', label: 'San Diego', countryCode: 'US' },
  // US — Tier 2 growing tech cities
  { slug: 'atlanta', label: 'Atlanta', countryCode: 'US' },
  { slug: 'raleigh', label: 'Raleigh', countryCode: 'US' },
  { slug: 'charlotte', label: 'Charlotte', countryCode: 'US' },
  { slug: 'nashville', label: 'Nashville', countryCode: 'US' },
  { slug: 'phoenix', label: 'Phoenix', countryCode: 'US' },
  { slug: 'salt-lake-city', label: 'Salt Lake City', countryCode: 'US' },
  { slug: 'minneapolis', label: 'Minneapolis', countryCode: 'US' },
  { slug: 'detroit', label: 'Detroit', countryCode: 'US' },
  { slug: 'pittsburgh', label: 'Pittsburgh', countryCode: 'US' },
  { slug: 'washington-dc', label: 'Washington DC', countryCode: 'US' },
  { slug: 'san-jose', label: 'San Jose', countryCode: 'US' },
  { slug: 'columbus', label: 'Columbus', countryCode: 'US' },
  { slug: 'indianapolis', label: 'Indianapolis', countryCode: 'US' },
  { slug: 'kansas-city', label: 'Kansas City', countryCode: 'US' },
  { slug: 'houston', label: 'Houston', countryCode: 'US' },
  { slug: 'philadelphia', label: 'Philadelphia', countryCode: 'US' },
  { slug: 'san-antonio', label: 'San Antonio', countryCode: 'US' },
  { slug: 'orlando', label: 'Orlando', countryCode: 'US' },
  { slug: 'st-louis', label: 'St. Louis', countryCode: 'US' },
  { slug: 'baltimore', label: 'Baltimore', countryCode: 'US' },
  { slug: 'las-vegas', label: 'Las Vegas', countryCode: 'US' },
  { slug: 'tampa', label: 'Tampa', countryCode: 'US' },
  { slug: 'richmond', label: 'Richmond', countryCode: 'US' },
  // Canada
  { slug: 'toronto', label: 'Toronto', countryCode: 'CA' },
  { slug: 'vancouver', label: 'Vancouver', countryCode: 'CA' },
  { slug: 'montreal', label: 'Montreal', countryCode: 'CA' },
  { slug: 'calgary', label: 'Calgary', countryCode: 'CA' },
  { slug: 'ottawa', label: 'Ottawa', countryCode: 'CA' },
  // UK & Ireland
  { slug: 'london', label: 'London', countryCode: 'GB' },
  { slug: 'manchester', label: 'Manchester', countryCode: 'GB' },
  { slug: 'edinburgh', label: 'Edinburgh', countryCode: 'GB' },
  { slug: 'birmingham', label: 'Birmingham', countryCode: 'GB' },
  { slug: 'bristol', label: 'Bristol', countryCode: 'GB' },
  { slug: 'dublin', label: 'Dublin', countryCode: 'IE' },
  // Europe
  { slug: 'berlin', label: 'Berlin', countryCode: 'DE' },
  { slug: 'munich', label: 'Munich', countryCode: 'DE' },
  { slug: 'hamburg', label: 'Hamburg', countryCode: 'DE' },
  { slug: 'amsterdam', label: 'Amsterdam', countryCode: 'NL' },
  { slug: 'paris', label: 'Paris', countryCode: 'FR' },
  { slug: 'barcelona', label: 'Barcelona', countryCode: 'ES' },
  { slug: 'madrid', label: 'Madrid', countryCode: 'ES' },
  { slug: 'stockholm', label: 'Stockholm', countryCode: 'SE' },
  { slug: 'copenhagen', label: 'Copenhagen', countryCode: 'DK' },
  { slug: 'zurich', label: 'Zurich', countryCode: 'CH' },
  { slug: 'lisbon', label: 'Lisbon', countryCode: 'PT' },
  { slug: 'warsaw', label: 'Warsaw', countryCode: 'PL' },
  { slug: 'prague', label: 'Prague', countryCode: 'CZ' },
  // Asia-Pacific
  { slug: 'singapore', label: 'Singapore', countryCode: 'SG' },
  { slug: 'sydney', label: 'Sydney', countryCode: 'AU' },
  { slug: 'melbourne', label: 'Melbourne', countryCode: 'AU' },
  { slug: 'bangalore', label: 'Bangalore', countryCode: 'IN' },
  { slug: 'hyderabad', label: 'Hyderabad', countryCode: 'IN' },
  { slug: 'tokyo', label: 'Tokyo', countryCode: 'JP' },
  { slug: 'hong-kong', label: 'Hong Kong', countryCode: 'HK' },
  { slug: 'tel-aviv', label: 'Tel Aviv', countryCode: 'IL' },
  { slug: 'dubai', label: 'Dubai', countryCode: 'AE' },
]

export const CITY_TARGET_SLUG_SET = new Set(CITY_TARGETS.map((city) => city.slug))
