// lib/roles/searchRoles.ts
// Broad role/type list for search dropdowns (mirrors examples in the provided UI screenshots)

export type SearchRoleOption = {
  slug: string
  label: string
  emoji: string
}

export const SEARCH_ROLE_OPTIONS: SearchRoleOption[] = [
  // Creative / Design
  { slug: '2d-artist', label: '2D Artist', emoji: '🎨' },
  { slug: '3d-artist', label: '3D Artist', emoji: '🗿' },
  { slug: 'art-director', label: 'Art Director', emoji: '🎭' },
  { slug: 'graphic-designer', label: 'Graphics Designer', emoji: '✍️' },
  { slug: 'creative-strategist', label: 'Creative Strategist', emoji: '🎨' },
  { slug: 'brand-designer', label: 'Brand Designer', emoji: '🎨' },
  { slug: 'brand-ambassador', label: 'Brand Ambassador', emoji: '🎭' },
  { slug: 'product-designer', label: 'Product Designer (UI/UX)', emoji: '🎨' },
  { slug: 'web-designer', label: 'Web Designer', emoji: '🕸️' },
  { slug: 'video-editor', label: 'Video Editor', emoji: '🎬' },

  // Writing / Content / Comms
  { slug: 'content-marketing-manager', label: 'Content Marketing Manager', emoji: '🖋️' },
  { slug: 'content-manager', label: 'Content Manager', emoji: '👩‍💻' },
  { slug: 'content-writer', label: 'Content Writer', emoji: '✏️' },
  { slug: 'copywriter', label: 'Copywriter', emoji: '📝' },
  { slug: 'content-creator', label: 'Content Creator', emoji: '💼' },
  { slug: 'public-relations', label: 'Public Relations (PR)', emoji: '📰' },
  { slug: 'communications', label: 'Communications', emoji: '📢' },

  // Sales / GTM
  { slug: 'account-executive', label: 'Account Executive', emoji: '🧑‍💼' },
  { slug: 'account-manager', label: 'Account Manager', emoji: '💰' },
  { slug: 'customer-success', label: 'Customer Success', emoji: '🏆' },
  { slug: 'customer-support', label: 'Customer Support', emoji: '💖' },
  { slug: 'customer-retention-specialist', label: 'Customer Retention Specialist', emoji: '🔄' },
  { slug: 'sales-development-representative', label: 'Sales Development (SDR)', emoji: '💸' },
  { slug: 'sales-engineer', label: 'Sales Engineer', emoji: '🧭' },
  { slug: 'sales-operations', label: 'Sales Operations', emoji: '📊' },
  { slug: 'revenue-operations', label: 'Revenue Operations', emoji: '✅' },
  { slug: 'inside-sales', label: 'Inside Sales', emoji: '⬇️' },
  { slug: 'outside-sales', label: 'Outside Sales', emoji: '🌆' },
  { slug: 'pre-sales-engineer', label: 'Pre-sales Engineer', emoji: '🔍' },
  { slug: 'salesforce-administrator', label: 'Salesforce Administrator', emoji: '🌐🧑‍💼' },
  { slug: 'salesforce-analyst', label: 'Salesforce Analyst', emoji: '🌐🧑‍💻' },
  { slug: 'client-partner', label: 'Client Partner', emoji: '🤝' },
  { slug: 'client-services', label: 'Client Services', emoji: '🗂️' },

  // Marketing / Growth
  { slug: 'marketing', label: 'Marketing', emoji: '🎡' },
  { slug: 'marketing-analyst', label: 'Marketing Analyst', emoji: '📊' },
  { slug: 'marketing-operations', label: 'Marketing Operations', emoji: '⚙️' },
  { slug: 'growth-marketing', label: 'Growth Marketing', emoji: '📈' },
  { slug: 'performance-marketing', label: 'Performance Marketing', emoji: '📈' },
  { slug: 'seo-marketing', label: 'SEO Marketing', emoji: '📉' },
  { slug: 'email-marketing-manager', label: 'Email Marketing Manager', emoji: '✉️' },
  { slug: 'digital-marketing', label: 'Digital Marketing', emoji: '🌐' },
  { slug: 'social-media-manager', label: 'Social Media Manager', emoji: '💕' },
  { slug: 'influencer-marketing', label: 'Influencer Marketing', emoji: '💅' },
  { slug: 'product-marketing', label: 'Product Marketing', emoji: '🎁' },

  // Product / Program / Ops
  { slug: 'product-manager', label: 'Product Manager', emoji: '✅' },
  { slug: 'product-operations', label: 'Product Operations', emoji: '⚡' },
  { slug: 'product-specialist', label: 'Product Specialist', emoji: '🪄' },
  { slug: 'program-manager', label: 'Program Manager', emoji: '📋' },
  { slug: 'project-manager', label: 'Project Manager', emoji: '👷' },
  { slug: 'technical-program-manager', label: 'Technical Program Manager', emoji: '🔧' },
  { slug: 'technical-project-manager', label: 'Technical Project Manager', emoji: '🧠' },
  { slug: 'product-analyst', label: 'Product Analyst', emoji: '🔍' },
  { slug: 'product-adoption-specialist', label: 'Product Adoption Specialist', emoji: '🌱' },

  // Engineering (software + infra)
  { slug: 'software-engineer', label: 'Software Engineer', emoji: '💻' },
  { slug: 'backend-engineer', label: 'Backend Engineer', emoji: '🖥️' },
  { slug: 'frontend-engineer', label: 'Frontend Engineer / Web Developer', emoji: '🖥️' },
  { slug: 'full-stack-engineer', label: 'Full-stack Engineer', emoji: '🧑‍💻' },
  { slug: 'android-engineer', label: 'Android Engineer', emoji: '🤖' },
  { slug: 'ios-engineer', label: 'iOS Engineer', emoji: '🍏' },
  { slug: 'devops-engineer', label: 'DevOps & Site Reliability Engineer (SRE)', emoji: '🚨' },
  { slug: 'platform-engineer', label: 'Platform Engineer', emoji: '🏗️' },
  { slug: 'application-engineer', label: 'Application Engineer', emoji: '💻' },
  { slug: 'systems-engineer', label: 'Systems Engineer', emoji: '⚙️' },
  { slug: 'solutions-engineer', label: 'Solutions Engineer', emoji: '💻' },
  { slug: 'qa-engineer', label: 'QA Engineer (Quality Assurance)', emoji: '🔧' },
  { slug: 'qa-automation-engineer', label: 'QA Automation Engineer', emoji: '🤖' },
  { slug: 'security-engineer', label: 'Cybersecurity / Security Engineer', emoji: '🛡️' },
  { slug: 'security-analyst', label: 'Security Analyst', emoji: '🔒' },
  { slug: 'incident-response-analyst', label: 'Incident Response Analyst', emoji: '🩸' },
  { slug: 'threat-intelligence-specialist', label: 'Threat Intelligence Specialist', emoji: '🕵️‍♂️' },
  { slug: 'hardware-engineer', label: 'Hardware Engineer', emoji: '🔧' },
  { slug: 'field-service-engineer', label: 'Field Service Engineer', emoji: '🔧' },
  { slug: 'implementation-specialist', label: 'Implementation Specialist', emoji: '🛠️' },
  { slug: 'service-now', label: 'ServiceNow', emoji: '🔧' },
  { slug: 'sap-consultant', label: 'SAP Consultant', emoji: '🖥️' },
  { slug: 'smart-contract-engineer', label: 'Smart Contract Engineer', emoji: '📜' },
  { slug: 'solutions-architect', label: 'Architect', emoji: '🏛️' },

  // Data / Analytics / ML
  { slug: 'data-analyst', label: 'Data Analyst', emoji: '📄' },
  { slug: 'data-engineer', label: 'Data Engineer', emoji: '🧪' },
  { slug: 'data-scientist', label: 'Data Scientist', emoji: '📊' },
  { slug: 'analytics-engineer', label: 'Analytics Engineer', emoji: '📊' },
  { slug: 'business-analyst', label: 'Business Analyst', emoji: '🤔' },
  { slug: 'business-intelligence-analyst', label: 'Business Intelligence Analyst', emoji: '📚' },
  { slug: 'business-intelligence-developer', label: 'Business Intelligence Developer', emoji: '📊' },
  { slug: 'database-administrator', label: 'Database Administrator', emoji: '💿' },
  { slug: 'data-entry', label: 'Data Entry', emoji: '⬇️' },
  { slug: 'ml-engineer', label: 'Machine Learning Engineer', emoji: '🤖' },
  { slug: 'ml-researcher', label: 'Research Scientist', emoji: '🧪' },
  { slug: 'llm-engineer', label: 'LLM Engineer', emoji: '🧠' },
  { slug: 'ai-engineer', label: 'AI Engineer', emoji: '🤖' },
  { slug: 'ai-research-scientist', label: 'AI Research Scientist', emoji: '🧠' },
  { slug: 'computer-vision-engineer', label: 'Computer Vision Engineer', emoji: '👁️' },
  { slug: 'nlp-engineer', label: 'NLP Engineer', emoji: '📜' },

  // Finance / Accounting / Legal
  { slug: 'accounting-manager', label: 'Accounting Manager', emoji: '🧾' },
  { slug: 'accountant', label: 'Accountant / Accounting', emoji: '💲' },
  { slug: 'accounts-payable', label: 'Accounts Payable', emoji: '🧾' },
  { slug: 'accounts-receivable', label: 'Accounts Receivable', emoji: '🧾' },
  { slug: 'financial-controller', label: 'Financial Controller', emoji: '⛔' },
  { slug: 'financial-planning-analysis', label: 'Financial Planning and Analysis (FP&A)', emoji: '🐝' },
  { slug: 'aml-financial-crime', label: 'AML and Financial Crime', emoji: '🆘' },
  { slug: 'tax', label: 'Tax', emoji: '💰' },
  { slug: 'pricing-analyst', label: 'Pricing Analyst', emoji: '💰' },
  { slug: 'payroll', label: 'Payroll', emoji: '🧾' },
  { slug: 'actuary', label: 'Actuary', emoji: '📊' },
  { slug: 'underwriter', label: 'Underwriter', emoji: '📋' },
  { slug: 'legal-assistant', label: 'Legal Assistant', emoji: '⚖️' },
  { slug: 'paralegal', label: 'Paralegal', emoji: '💼' },
  { slug: 'general-counsel', label: 'General Counsel', emoji: '🧠' },

  // People / HR / Recruiting
  { slug: 'people-operations', label: 'People Operations', emoji: '👥' },
  { slug: 'human-resources', label: 'Human Resources (HR)', emoji: '🧑‍🤝‍🧑' },
  { slug: 'recruiter', label: 'Recruiter', emoji: '🎯' },
  { slug: 'technical-recruiter', label: 'Technical Recruiter', emoji: '👀' },
  { slug: 'technical-account-manager', label: 'Technical Account Manager', emoji: '🧑‍💼' },
  { slug: 'technical-customer-success-manager', label: 'Technical Customer Success Manager', emoji: '🧑‍💼' },

  // Ops / Admin
  { slug: 'operations', label: 'Operations', emoji: '⚙️' },
  { slug: 'business-operations', label: 'Business Operations', emoji: '⚙️' },
  { slug: 'administration', label: 'Administration', emoji: '💻' },
  { slug: 'administrative-assistant', label: 'Administrative Assistant', emoji: '🗒️' },
  { slug: 'executive-assistant', label: 'Executive Assistant', emoji: '🧑‍💼' },
  { slug: 'office-manager', label: 'Manager', emoji: '🏢' },
  { slug: 'strategy', label: 'Strategy', emoji: '🧠' },
  { slug: 'supply-chain', label: 'Supply Chain', emoji: '🔗' },
  { slug: 'procurement', label: 'Procurement', emoji: '🛒' },
  { slug: 'operations-manager', label: 'Operations Manager', emoji: '⚙️' },
  { slug: 'program-manager', label: 'Program Manager', emoji: '📋' },

  // Leadership
  { slug: 'chief-operating-officer', label: 'Chief Operating Officer (COO)', emoji: '🏢' },
  { slug: 'chief-technology-officer', label: 'Chief Technology Officer (CTO)', emoji: '👩‍💻' },
  { slug: 'chief-marketing-officer', label: 'Chief Marketing Officer (CMO)', emoji: '🎯' },
  { slug: 'chief-of-staff', label: 'Chief of Staff', emoji: '🧑‍✈️' },
  { slug: 'vice-president', label: 'Vice President', emoji: '🏢' },
  { slug: 'director', label: 'Director', emoji: '🧭' },
  { slug: 'manager', label: 'Manager', emoji: '🏙️' },

  // Healthcare / Bio
  { slug: 'clinical-operations', label: 'Clinical Operations', emoji: '🏥' },
  { slug: 'clinical-research', label: 'Clinical Research', emoji: '🧪' },
  { slug: 'medical-director', label: 'Medical Director', emoji: '🧑‍⚕️' },
  { slug: 'medical-reviewer', label: 'Medical Reviewer', emoji: '🔍🏥' },
  { slug: 'therapist', label: 'Therapist', emoji: '🧠' },

  // Engineering (hardware / mech / civil)
  { slug: 'electrical-engineer', label: 'Electrical Engineer', emoji: '🔋' },
  { slug: 'mechanical-engineer', label: 'Mechanical Engineer', emoji: '🧑‍🔧' },
  { slug: 'civil-engineer', label: 'Civil Engineer', emoji: '🗼' },

  // Science / Research
  { slug: 'research-analyst', label: 'Research Analyst', emoji: '🔬' },
  { slug: 'research-engineer', label: 'Research Engineer', emoji: '📚' },
  { slug: 'research-scientist', label: 'Research Scientist', emoji: '🧪' },

  // Other specialized roles
  { slug: 'bookkeeping', label: 'Bookkeeping and Clerks', emoji: '👩‍💼' },
  { slug: 'billing-specialist', label: 'Billing Specialist', emoji: '📊' },
  { slug: 'collections', label: 'Collections', emoji: '📞' },
  { slug: 'call-center-representative', label: 'Call Center Representative', emoji: '☎️' },
  { slug: 'community-manager', label: 'Community Manager', emoji: '🧑‍🤝‍🧑' },
  { slug: 'compliance', label: 'Compliance', emoji: '🚗' },
  { slug: 'consultant', label: 'Consultant', emoji: '💼' },
  { slug: 'counselor', label: 'Counselor', emoji: '🧘' },
  { slug: 'crypto', label: 'Crypto', emoji: '฿' },
  { slug: 'customer-advocate', label: 'Customer Advocate', emoji: '🗣️' },
  { slug: 'defi', label: 'DeFi', emoji: '🏦' },
  { slug: 'developer-relations', label: 'Developer Relations (DevRel)', emoji: '🤝' },
  { slug: 'ecommerce', label: 'E-commerce', emoji: '🛍️' },
  { slug: 'events', label: 'Events', emoji: '🎪' },
  { slug: 'game-engineer', label: 'Game Engineer', emoji: '🎮' },
  { slug: 'human-resources', label: 'Human Resources (HR)', emoji: '👥' },
  { slug: 'implementation-specialist', label: 'Implementation Specialist', emoji: '🛠️' },
  { slug: 'insurance', label: 'Insurance', emoji: '🔒' },
  { slug: 'it-support', label: 'IT Support', emoji: '💻' },
  { slug: 'journalist', label: 'Journalist', emoji: '🖥️' },
  { slug: 'lead-generation', label: 'Lead Generation', emoji: '📡' },
  { slug: 'learning-and-development', label: 'Learning and Development', emoji: '📚' },
  { slug: 'network-engineer', label: 'Network Engineer', emoji: '📡' },
  { slug: 'network-operations', label: 'Network Operations', emoji: '🌐' },
  { slug: 'notary', label: 'Notary', emoji: '📜' },
  { slug: 'onboarding-specialist', label: 'Onboarding Specialist', emoji: '🚀' },
  { slug: 'operations-analyst', label: 'Operations', emoji: '⚙️' },
  { slug: 'people-operations', label: 'People Operations', emoji: '👥' },
  { slug: 'platform-engineer', label: 'Platform Engineer', emoji: '🏗️' },
  { slug: 'pricing-analyst', label: 'Pricing Analyst', emoji: '💰' },
  { slug: 'producer', label: 'Producer', emoji: '🍿' },
  { slug: 'program-manager', label: 'Program Manager', emoji: '📋' },
  { slug: 'proposal-manager', label: 'Proposal Manager', emoji: '📄' },
  { slug: 'qa-engineer', label: 'QA Engineer (Quality Assurance)', emoji: '🔧' },
  { slug: 'qa-automation-engineer', label: 'QA Automation Engineer', emoji: '🤖' },
  { slug: 'recruiter', label: 'Recruiter', emoji: '🎯' },
  { slug: 'research-analyst', label: 'Research Analyst', emoji: '🔬' },
  { slug: 'research-engineer', label: 'Research Engineer', emoji: '📚' },
  { slug: 'research-scientist', label: 'Research Scientist', emoji: '🧪' },
  { slug: 'risk', label: 'Risk', emoji: '🎲' },
  { slug: 'robotics', label: 'Robotics', emoji: '🤖' },
  { slug: 'sap-consultant', label: 'SAP Consultant', emoji: '🖥️' },
  { slug: 'scrum-master', label: 'Scrum Master + Agile Coach', emoji: '⚡' },
  { slug: 'security-operations', label: 'Security Operations', emoji: '🛡️' },
  { slug: 'servicenow', label: 'ServiceNow', emoji: '🔧' },
  { slug: 'smart-contract-engineer', label: 'Smart Contract Engineer', emoji: '📜' },
  { slug: 'social-media-manager', label: 'Social Media Manager', emoji: '💕' },
  { slug: 'solutions-engineer', label: 'Solutions Engineer', emoji: '💻' },
  { slug: 'software-development-engineer-test', label: 'Software Development Engineer in Test', emoji: '⚡' },
  { slug: 'software-engineer', label: 'Software Engineer', emoji: '💻' },
  { slug: 'support-engineer', label: 'Support Engineer', emoji: '📞' },
  { slug: 'systems-administrator', label: 'Systems Administrator', emoji: '🖥️' },
  { slug: 'tax', label: 'Tax', emoji: '💰' },
  { slug: 'technical-writer', label: 'Technical Writer', emoji: '✍️' },
  { slug: 'technical-product-manager', label: 'Technical Product Manager (TPM)', emoji: '⚒️' },
  { slug: 'translator', label: 'Translator / Interpreter', emoji: '🌍' },
  { slug: 'ux-researcher', label: 'UX Researcher', emoji: '🧪' },
  { slug: 'web3', label: 'Web3', emoji: '🌐' },
]
