import { format as __format } from 'node:util'
import { PrismaClient } from '@prisma/client'

const __slog = (...args: any[]) => process.stdout.write(__format(...args) + "\n")
const __serr = (...args: any[]) => process.stderr.write(__format(...args) + "\n")

const prisma = new PrismaClient()

function slugify(name: string): string {
  return name.toLowerCase().replace(/&/g, '-and-').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}

const COMPANIES = [
  // AI/ML
  { name: 'OpenAI', ats: 'https://boards.greenhouse.io/openai' },
  { name: 'Anthropic', ats: 'https://boards.greenhouse.io/anthropic' },
  { name: 'Cohere', ats: 'https://jobs.lever.co/cohere' },
  { name: 'Hugging Face', ats: 'https://apply.workable.com/huggingface' },
  { name: 'Scale AI', ats: 'https://boards.greenhouse.io/scaleai' },
  { name: 'Replicate', ats: 'https://boards.greenhouse.io/replicate' },
  { name: 'Weights & Biases', ats: 'https://boards.greenhouse.io/wandb' },
  { name: 'Runway', ats: 'https://boards.greenhouse.io/runwayml' },
  { name: 'Stability AI', ats: 'https://jobs.lever.co/stability' },
  { name: 'Midjourney', ats: 'https://boards.greenhouse.io/midjourney' },
  { name: 'Jasper', ats: 'https://boards.greenhouse.io/jasper' },
  { name: 'Writer', ats: 'https://boards.greenhouse.io/writer' },
  { name: 'Character AI', ats: 'https://boards.greenhouse.io/character' },
  { name: 'Perplexity', ats: 'https://boards.greenhouse.io/perplexity' },
  { name: 'Together AI', ats: 'https://boards.greenhouse.io/togetherai' },
  { name: 'Anyscale', ats: 'https://boards.greenhouse.io/anyscale' },
  { name: 'Modal', ats: 'https://boards.greenhouse.io/modal' },
  { name: 'Pinecone', ats: 'https://boards.greenhouse.io/pinecone' },
  { name: 'Weaviate', ats: 'https://boards.greenhouse.io/weaviate' },
  { name: 'LangChain', ats: 'https://boards.greenhouse.io/langchain' },
  { name: 'Deepgram', ats: 'https://boards.greenhouse.io/deepgram' },
  { name: 'AssemblyAI', ats: 'https://boards.greenhouse.io/assemblyai' },
  { name: 'Eleven Labs', ats: 'https://jobs.lever.co/elevenlabs' },
  { name: 'Descript', ats: 'https://boards.greenhouse.io/descript' },
  // Dev Tools
  { name: 'GitHub', ats: 'https://boards.greenhouse.io/github' },
  { name: 'GitLab', ats: 'https://boards.greenhouse.io/gitlab' },
  { name: 'Vercel', ats: 'https://boards.greenhouse.io/vercel' },
  { name: 'Netlify', ats: 'https://boards.greenhouse.io/netlify' },
  { name: 'Supabase', ats: 'https://boards.greenhouse.io/supabase' },
  { name: 'PlanetScale', ats: 'https://boards.greenhouse.io/planetscale' },
  { name: 'Neon', ats: 'https://boards.greenhouse.io/neondatabase' },
  { name: 'Railway', ats: 'https://boards.greenhouse.io/railway' },
  { name: 'Render', ats: 'https://boards.greenhouse.io/render' },
  { name: 'Fly.io', ats: 'https://boards.greenhouse.io/flyio' },
  { name: 'Cloudflare', ats: 'https://boards.greenhouse.io/cloudflare' },
  { name: 'Fastly', ats: 'https://boards.greenhouse.io/fastly' },
  { name: 'HashiCorp', ats: 'https://boards.greenhouse.io/hashicorp' },
  { name: 'Docker', ats: 'https://boards.greenhouse.io/docker' },
  { name: 'Postman', ats: 'https://boards.greenhouse.io/postman' },
  { name: 'Sourcegraph', ats: 'https://boards.greenhouse.io/sourcegraph' },
  { name: 'Snyk', ats: 'https://boards.greenhouse.io/snyk' },
  { name: 'Sentry', ats: 'https://boards.greenhouse.io/sentry' },
  { name: 'LaunchDarkly', ats: 'https://boards.greenhouse.io/launchdarkly' },
  { name: 'CircleCI', ats: 'https://boards.greenhouse.io/circleci' },
  { name: 'Pulumi', ats: 'https://boards.greenhouse.io/pulumi' },
  { name: '1Password', ats: 'https://boards.greenhouse.io/1password' },
  { name: 'Tailscale', ats: 'https://boards.greenhouse.io/tailscale' },
  { name: 'Kong', ats: 'https://boards.greenhouse.io/kong' },
  { name: 'Algolia', ats: 'https://boards.greenhouse.io/algolia' },
  { name: 'Prisma', ats: 'https://boards.greenhouse.io/prisma' },
  { name: 'Hasura', ats: 'https://boards.greenhouse.io/hasura' },
  { name: 'Apollo GraphQL', ats: 'https://boards.greenhouse.io/apollographql' },
  { name: 'Contentful', ats: 'https://boards.greenhouse.io/contentful' },
  { name: 'Sanity', ats: 'https://boards.greenhouse.io/sanity' },
  // Data
  { name: 'Databricks', ats: 'https://boards.greenhouse.io/databricks' },
  { name: 'Snowflake', ats: 'https://boards.greenhouse.io/snowflake' },
  { name: 'dbt Labs', ats: 'https://boards.greenhouse.io/dbtlabs' },
  { name: 'Fivetran', ats: 'https://boards.greenhouse.io/fivetran' },
  { name: 'Airbyte', ats: 'https://boards.greenhouse.io/airbyte' },
  { name: 'Census', ats: 'https://boards.greenhouse.io/census' },
  { name: 'Hightouch', ats: 'https://boards.greenhouse.io/hightouch' },
  { name: 'Hex', ats: 'https://boards.greenhouse.io/hex' },
  { name: 'Metabase', ats: 'https://boards.greenhouse.io/metabase' },
  { name: 'Amplitude', ats: 'https://boards.greenhouse.io/amplitude' },
  { name: 'Mixpanel', ats: 'https://boards.greenhouse.io/mixpanel' },
  { name: 'PostHog', ats: 'https://boards.greenhouse.io/posthog' },
  { name: 'Segment', ats: 'https://boards.greenhouse.io/segment' },
  { name: 'Monte Carlo', ats: 'https://boards.greenhouse.io/montecarlodata' },
  // Infrastructure
  { name: 'Cockroach Labs', ats: 'https://boards.greenhouse.io/cockroachlabs' },
  { name: 'Timescale', ats: 'https://boards.greenhouse.io/timescale' },
  { name: 'ClickHouse', ats: 'https://boards.greenhouse.io/clickhouse' },
  { name: 'Confluent', ats: 'https://boards.greenhouse.io/confluent' },
  { name: 'Redpanda', ats: 'https://boards.greenhouse.io/redpanda' },
  { name: 'Temporal', ats: 'https://boards.greenhouse.io/temporal' },
  { name: 'Grafana Labs', ats: 'https://boards.greenhouse.io/grafanalabs' },
  { name: 'Datadog', ats: 'https://boards.greenhouse.io/datadog' },
  { name: 'New Relic', ats: 'https://boards.greenhouse.io/newrelic' },
  { name: 'Honeycomb', ats: 'https://boards.greenhouse.io/honeycomb' },
  { name: 'Cribl', ats: 'https://boards.greenhouse.io/cribl' },
  { name: 'Teleport', ats: 'https://boards.greenhouse.io/teleport' },
  // Fintech
  { name: 'Stripe', ats: 'https://boards.greenhouse.io/stripe' },
  { name: 'Plaid', ats: 'https://boards.greenhouse.io/plaid' },
  { name: 'Brex', ats: 'https://boards.greenhouse.io/brex' },
  { name: 'Ramp', ats: 'https://boards.greenhouse.io/ramp' },
  { name: 'Mercury', ats: 'https://boards.greenhouse.io/mercury' },
  { name: 'Coinbase', ats: 'https://boards.greenhouse.io/coinbase' },
  { name: 'Robinhood', ats: 'https://boards.greenhouse.io/robinhood' },
  { name: 'Affirm', ats: 'https://boards.greenhouse.io/affirm' },
  { name: 'Klarna', ats: 'https://boards.greenhouse.io/klarna' },
  { name: 'Wise', ats: 'https://boards.greenhouse.io/wise' },
  { name: 'Checkout.com', ats: 'https://boards.greenhouse.io/checkoutcom' },
  { name: 'Marqeta', ats: 'https://boards.greenhouse.io/marqeta' },
  { name: 'Modern Treasury', ats: 'https://boards.greenhouse.io/moderntreasury' },
  { name: 'Alloy', ats: 'https://boards.greenhouse.io/alloy' },
  { name: 'Persona', ats: 'https://boards.greenhouse.io/persona' },
  // HR
  { name: 'Rippling', ats: 'https://boards.greenhouse.io/rippling' },
  { name: 'Gusto', ats: 'https://boards.greenhouse.io/gusto' },
  { name: 'Deel', ats: 'https://boards.greenhouse.io/deel' },
  { name: 'Remote', ats: 'https://boards.greenhouse.io/remotecom' },
  { name: 'Oyster', ats: 'https://boards.greenhouse.io/oyster' },
  { name: 'Lattice', ats: 'https://boards.greenhouse.io/lattice' },
  { name: 'Culture Amp', ats: 'https://boards.greenhouse.io/cultureamp' },
  { name: 'Ashby', ats: 'https://boards.greenhouse.io/ashby' },
  { name: 'Lever', ats: 'https://jobs.lever.co/lever' },
  { name: 'Greenhouse', ats: 'https://boards.greenhouse.io/greenhouse' },
  { name: 'Checkr', ats: 'https://boards.greenhouse.io/checkr' },
  // Productivity
  { name: 'Notion', ats: 'https://boards.greenhouse.io/notion' },
  { name: 'Coda', ats: 'https://boards.greenhouse.io/coda' },
  { name: 'Airtable', ats: 'https://boards.greenhouse.io/airtable' },
  { name: 'Monday.com', ats: 'https://boards.greenhouse.io/mondaycom' },
  { name: 'Asana', ats: 'https://boards.greenhouse.io/asana' },
  { name: 'ClickUp', ats: 'https://boards.greenhouse.io/clickup' },
  { name: 'Linear', ats: 'https://boards.greenhouse.io/linear' },
  { name: 'Slack', ats: 'https://boards.greenhouse.io/slack' },
  { name: 'Discord', ats: 'https://boards.greenhouse.io/discord' },
  { name: 'Loom', ats: 'https://boards.greenhouse.io/loom' },
  { name: 'Miro', ats: 'https://boards.greenhouse.io/miro' },
  { name: 'Figma', ats: 'https://boards.greenhouse.io/figma' },
  { name: 'Canva', ats: 'https://boards.greenhouse.io/canva' },
  { name: 'Framer', ats: 'https://boards.greenhouse.io/framer' },
  { name: 'Webflow', ats: 'https://boards.greenhouse.io/webflow' },
  { name: 'Zapier', ats: 'https://boards.greenhouse.io/zapier' },
  { name: 'Calendly', ats: 'https://boards.greenhouse.io/calendly' },
  { name: 'Dropbox', ats: 'https://boards.greenhouse.io/dropbox' },
  { name: 'DocuSign', ats: 'https://boards.greenhouse.io/docusign' },
  { name: 'Typeform', ats: 'https://boards.greenhouse.io/typeform' },
  // Sales & CRM
  { name: 'HubSpot', ats: 'https://boards.greenhouse.io/hubspot' },
  { name: 'Pipedrive', ats: 'https://boards.greenhouse.io/pipedrive' },
  { name: 'Attio', ats: 'https://boards.greenhouse.io/attio' },
  { name: 'Gong', ats: 'https://boards.greenhouse.io/gong' },
  { name: 'Clari', ats: 'https://boards.greenhouse.io/clari' },
  { name: 'Outreach', ats: 'https://boards.greenhouse.io/outreach' },
  { name: 'Apollo', ats: 'https://boards.greenhouse.io/apollo' },
  { name: 'ZoomInfo', ats: 'https://boards.greenhouse.io/zoominfo' },
  { name: 'Clay', ats: 'https://boards.greenhouse.io/clay' },
  // Marketing
  { name: 'Klaviyo', ats: 'https://boards.greenhouse.io/klaviyo' },
  { name: 'Customer.io', ats: 'https://boards.greenhouse.io/customerio' },
  { name: 'Braze', ats: 'https://boards.greenhouse.io/braze' },
  { name: 'Iterable', ats: 'https://boards.greenhouse.io/iterable' },
  { name: 'Twilio', ats: 'https://boards.greenhouse.io/twilio' },
  { name: 'Attentive', ats: 'https://boards.greenhouse.io/attentive' },
  { name: 'Hotjar', ats: 'https://boards.greenhouse.io/hotjar' },
  { name: 'FullStory', ats: 'https://boards.greenhouse.io/fullstory' },
  { name: 'Pendo', ats: 'https://boards.greenhouse.io/pendo' },
  // Support
  { name: 'Zendesk', ats: 'https://boards.greenhouse.io/zendesk' },
  { name: 'Intercom', ats: 'https://boards.greenhouse.io/intercom' },
  { name: 'Front', ats: 'https://boards.greenhouse.io/front' },
  { name: 'Help Scout', ats: 'https://boards.greenhouse.io/helpscout' },
  { name: 'Gainsight', ats: 'https://boards.greenhouse.io/gainsight' },
  // Security
  { name: 'CrowdStrike', ats: 'https://boards.greenhouse.io/crowdstrike' },
  { name: 'SentinelOne', ats: 'https://boards.greenhouse.io/sentinelone' },
  { name: 'Okta', ats: 'https://boards.greenhouse.io/okta' },
  { name: 'Auth0', ats: 'https://boards.greenhouse.io/auth0' },
  { name: 'Stytch', ats: 'https://boards.greenhouse.io/stytch' },
  { name: 'WorkOS', ats: 'https://boards.greenhouse.io/workos' },
  { name: 'Clerk', ats: 'https://boards.greenhouse.io/clerk' },
  { name: 'Vanta', ats: 'https://boards.greenhouse.io/vanta' },
  { name: 'Drata', ats: 'https://boards.greenhouse.io/drata' },
  { name: 'Wiz', ats: 'https://boards.greenhouse.io/wiz' },
  { name: 'Snyk', ats: 'https://boards.greenhouse.io/snyk' },
  // E-commerce
  { name: 'Shopify', ats: 'https://boards.greenhouse.io/shopify' },
  { name: 'BigCommerce', ats: 'https://boards.greenhouse.io/bigcommerce' },
  { name: 'Faire', ats: 'https://boards.greenhouse.io/faire' },
  { name: 'Bolt', ats: 'https://boards.greenhouse.io/bolt' },
  { name: 'Recharge', ats: 'https://boards.greenhouse.io/recharge' },
  { name: 'ShipBob', ats: 'https://boards.greenhouse.io/shipbob' },
  { name: 'Flexport', ats: 'https://boards.greenhouse.io/flexport' },
  { name: 'Samsara', ats: 'https://boards.greenhouse.io/samsara' },
  // Consumer
  { name: 'Spotify', ats: 'https://jobs.lever.co/spotify' },
  { name: 'Netflix', ats: 'https://jobs.lever.co/netflix' },
  { name: 'Reddit', ats: 'https://boards.greenhouse.io/reddit' },
  { name: 'Pinterest', ats: 'https://boards.greenhouse.io/pinterest' },
  { name: 'Snap', ats: 'https://boards.greenhouse.io/snap' },
  { name: 'Duolingo', ats: 'https://boards.greenhouse.io/duolingo' },
  { name: 'Headspace', ats: 'https://boards.greenhouse.io/headspace' },
  { name: 'Calm', ats: 'https://boards.greenhouse.io/calm' },
  { name: 'Strava', ats: 'https://boards.greenhouse.io/strava' },
  { name: 'AllTrails', ats: 'https://boards.greenhouse.io/alltrails' },
  { name: 'Whoop', ats: 'https://boards.greenhouse.io/whoop' },
  // Food
  { name: 'DoorDash', ats: 'https://boards.greenhouse.io/doordash' },
  { name: 'Instacart', ats: 'https://boards.greenhouse.io/instacart' },
  { name: 'Toast', ats: 'https://boards.greenhouse.io/toast' },
  { name: 'Square', ats: 'https://boards.greenhouse.io/square' },
  // Health
  { name: 'Tempus', ats: 'https://boards.greenhouse.io/tempus' },
  { name: 'Color', ats: 'https://boards.greenhouse.io/color' },
  { name: 'Ro', ats: 'https://boards.greenhouse.io/ro' },
  { name: 'Hims & Hers', ats: 'https://boards.greenhouse.io/himshers' },
  { name: 'Spring Health', ats: 'https://boards.greenhouse.io/springhealth' },
  { name: 'Lyra Health', ats: 'https://boards.greenhouse.io/lyrahealth' },
  { name: 'Modern Health', ats: 'https://boards.greenhouse.io/modernhealth' },
  { name: 'Headway', ats: 'https://boards.greenhouse.io/headway' },
  { name: 'Alma', ats: 'https://boards.greenhouse.io/alma' },
  { name: 'BetterUp', ats: 'https://boards.greenhouse.io/betterup' },
  { name: 'Sword Health', ats: 'https://boards.greenhouse.io/swordhealth' },
  { name: 'Hinge Health', ats: 'https://boards.greenhouse.io/hingehealth' },
  { name: 'Levels', ats: 'https://boards.greenhouse.io/levels' },
  // Real Estate
  { name: 'Airbnb', ats: 'https://boards.greenhouse.io/airbnb' },
  { name: 'Opendoor', ats: 'https://boards.greenhouse.io/opendoor' },
  { name: 'Redfin', ats: 'https://boards.greenhouse.io/redfin' },
  { name: 'Compass', ats: 'https://boards.greenhouse.io/compass' },
  { name: 'Procore', ats: 'https://boards.greenhouse.io/procore' },
  // Education
  { name: 'Coursera', ats: 'https://boards.greenhouse.io/coursera' },
  { name: 'Udemy', ats: 'https://boards.greenhouse.io/udemy' },
  { name: 'MasterClass', ats: 'https://boards.greenhouse.io/masterclass' },
  { name: 'Khan Academy', ats: 'https://boards.greenhouse.io/khanacademy' },
  { name: 'Quizlet', ats: 'https://boards.greenhouse.io/quizlet' },
  { name: 'Codecademy', ats: 'https://boards.greenhouse.io/codecademy' },
  { name: 'DataCamp', ats: 'https://boards.greenhouse.io/datacamp' },
  // Gaming
  { name: 'Roblox', ats: 'https://boards.greenhouse.io/roblox' },
  { name: 'Epic Games', ats: 'https://boards.greenhouse.io/epicgames' },
  { name: 'Unity', ats: 'https://boards.greenhouse.io/unity' },
  { name: 'Riot Games', ats: 'https://boards.greenhouse.io/riotgames' },
  // Climate
  { name: 'Tesla', ats: 'https://boards.greenhouse.io/tesla' },
  { name: 'Rivian', ats: 'https://boards.greenhouse.io/rivian' },
  { name: 'ChargePoint', ats: 'https://boards.greenhouse.io/chargepoint' },
  { name: 'Aurora Solar', ats: 'https://boards.greenhouse.io/aurorasolar' },
  { name: 'Watershed', ats: 'https://boards.greenhouse.io/watershed' },
  // Aerospace
  { name: 'SpaceX', ats: 'https://boards.greenhouse.io/spacex' },
  { name: 'Anduril', ats: 'https://boards.greenhouse.io/anduril' },
  { name: 'Planet Labs', ats: 'https://boards.greenhouse.io/planetlabs' },
  { name: 'Relativity Space', ats: 'https://boards.greenhouse.io/relativityspace' },
  { name: 'Zipline', ats: 'https://boards.greenhouse.io/zipline' },
  // More Lever companies
  { name: 'Lyft', ats: 'https://jobs.lever.co/lyft' },
  { name: 'Wealthfront', ats: 'https://jobs.lever.co/wealthfront' },
  { name: 'Betterment', ats: 'https://jobs.lever.co/betterment' },
  { name: 'Oscar Health', ats: 'https://jobs.lever.co/oscarhealth' },
  { name: 'Lemonade', ats: 'https://jobs.lever.co/lemonade' },
  { name: 'Next Insurance', ats: 'https://jobs.lever.co/nextinsurance' },
  { name: 'Coalition', ats: 'https://jobs.lever.co/coalition' },
  // More companies
  { name: 'Retool', ats: 'https://boards.greenhouse.io/retool' },
  { name: 'Resend', ats: 'https://boards.greenhouse.io/resend' },
  { name: 'Raycast', ats: 'https://boards.greenhouse.io/raycast' },
  { name: 'Cursor', ats: 'https://boards.greenhouse.io/cursor' },
  { name: 'Replit', ats: 'https://boards.greenhouse.io/replit' },
  { name: 'Codeium', ats: 'https://boards.greenhouse.io/codeium' },
  { name: 'Tabnine', ats: 'https://boards.greenhouse.io/tabnine' },
  { name: 'Sourcery', ats: 'https://boards.greenhouse.io/sourcery' },
  { name: 'Mintlify', ats: 'https://boards.greenhouse.io/mintlify' },
  { name: 'ReadMe', ats: 'https://boards.greenhouse.io/readme' },
  { name: 'GitBook', ats: 'https://boards.greenhouse.io/gitbook' },
  { name: 'Swimm', ats: 'https://boards.greenhouse.io/swimm' },
  { name: 'Linear', ats: 'https://boards.greenhouse.io/linear' },
  { name: 'Plane', ats: 'https://boards.greenhouse.io/plane' },
  { name: 'Tiptap', ats: 'https://boards.greenhouse.io/tiptap' },
  { name: 'Liveblocks', ats: 'https://boards.greenhouse.io/liveblocks' },
  { name: 'Partykit', ats: 'https://boards.greenhouse.io/partykit' },
  { name: 'Inngest', ats: 'https://boards.greenhouse.io/inngest' },
  { name: 'Knock', ats: 'https://boards.greenhouse.io/knock' },
  { name: 'Novu', ats: 'https://boards.greenhouse.io/novu' },
  { name: 'Loops', ats: 'https://boards.greenhouse.io/loops' },
  { name: 'Resend', ats: 'https://boards.greenhouse.io/resend' },
  { name: 'Plunk', ats: 'https://boards.greenhouse.io/plunk' },
  { name: 'Svix', ats: 'https://boards.greenhouse.io/svix' },
  { name: 'Hookdeck', ats: 'https://boards.greenhouse.io/hookdeck' },
  { name: 'Upstash', ats: 'https://boards.greenhouse.io/upstash' },
  { name: 'Tinybird', ats: 'https://boards.greenhouse.io/tinybird' },
  { name: 'Motherduck', ats: 'https://boards.greenhouse.io/motherduck' },
  { name: 'Turso', ats: 'https://boards.greenhouse.io/turso' },
  { name: 'EdgeDB', ats: 'https://boards.greenhouse.io/edgedb' },
  { name: 'SurrealDB', ats: 'https://boards.greenhouse.io/surrealdb' },
  { name: 'Convex', ats: 'https://boards.greenhouse.io/convex' },
  { name: 'Xata', ats: 'https://boards.greenhouse.io/xata' },
  { name: 'Tigris', ats: 'https://boards.greenhouse.io/tigris' },
  { name: 'Drizzle', ats: 'https://boards.greenhouse.io/drizzle' },
  { name: 'Zod', ats: 'https://boards.greenhouse.io/zod' },
  { name: 'tRPC', ats: 'https://boards.greenhouse.io/trpc' },
  { name: 'Hono', ats: 'https://boards.greenhouse.io/hono' },
  { name: 'Bun', ats: 'https://boards.greenhouse.io/bun' },
  { name: 'Deno', ats: 'https://boards.greenhouse.io/deno' },
  { name: 'Oven', ats: 'https://boards.greenhouse.io/oven' },
  { name: 'Rome', ats: 'https://boards.greenhouse.io/rome' },
  { name: 'Biome', ats: 'https://boards.greenhouse.io/biome' },
  { name: 'Oxc', ats: 'https://boards.greenhouse.io/oxc' },
  { name: 'Rspack', ats: 'https://boards.greenhouse.io/rspack' },
  { name: 'Turbopack', ats: 'https://boards.greenhouse.io/turbopack' },
  { name: 'Farm', ats: 'https://boards.greenhouse.io/farm' },
  { name: 'Vite', ats: 'https://boards.greenhouse.io/vite' },
  { name: 'Astro', ats: 'https://boards.greenhouse.io/astro' },
  { name: 'Qwik', ats: 'https://boards.greenhouse.io/qwik' },
  { name: 'Solid', ats: 'https://boards.greenhouse.io/solid' },
  { name: 'Svelte', ats: 'https://boards.greenhouse.io/svelte' },
  { name: 'Vue', ats: 'https://boards.greenhouse.io/vue' },
  { name: 'Nuxt', ats: 'https://boards.greenhouse.io/nuxt' },
  { name: 'Remix', ats: 'https://boards.greenhouse.io/remix' },
  { name: 'RedwoodJS', ats: 'https://boards.greenhouse.io/redwoodjs' },
  { name: 'Blitz', ats: 'https://boards.greenhouse.io/blitz' },
  { name: 'T3', ats: 'https://boards.greenhouse.io/t3' },
  { name: 'Create T3 App', ats: 'https://boards.greenhouse.io/createt3app' },
  { name: 'Payload', ats: 'https://boards.greenhouse.io/payload' },
  { name: 'Keystone', ats: 'https://boards.greenhouse.io/keystone' },
  { name: 'Directus', ats: 'https://boards.greenhouse.io/directus' },
  { name: 'Appwrite', ats: 'https://boards.greenhouse.io/appwrite' },
  { name: 'Pocketbase', ats: 'https://boards.greenhouse.io/pocketbase' },
  { name: 'Coolify', ats: 'https://boards.greenhouse.io/coolify' },
  { name: 'Dokku', ats: 'https://boards.greenhouse.io/dokku' },
  { name: 'Kamal', ats: 'https://boards.greenhouse.io/kamal' },
  { name: 'SST', ats: 'https://boards.greenhouse.io/sst' },
  { name: 'Seed', ats: 'https://boards.greenhouse.io/seed' },
  { name: 'Serverless', ats: 'https://boards.greenhouse.io/serverless' },
  { name: 'Architect', ats: 'https://boards.greenhouse.io/architect' },
  { name: 'Begin', ats: 'https://boards.greenhouse.io/begin' },
  { name: 'Nitric', ats: 'https://boards.greenhouse.io/nitric' },
  { name: 'Encore', ats: 'https://boards.greenhouse.io/encore' },
  { name: 'Buf', ats: 'https://boards.greenhouse.io/buf' },
  { name: 'Connect', ats: 'https://boards.greenhouse.io/connect' },
  { name: 'Protobuf', ats: 'https://boards.greenhouse.io/protobuf' },
  { name: 'gRPC', ats: 'https://boards.greenhouse.io/grpc' },
  { name: 'GraphQL', ats: 'https://boards.greenhouse.io/graphql' },
  { name: 'Stellate', ats: 'https://boards.greenhouse.io/stellate' },
  { name: 'WunderGraph', ats: 'https://boards.greenhouse.io/wundergraph' },
  { name: 'Grafbase', ats: 'https://boards.greenhouse.io/grafbase' },
  { name: 'Stepzen', ats: 'https://boards.greenhouse.io/stepzen' },
  { name: 'Buildkite', ats: 'https://boards.greenhouse.io/buildkite' },
  { name: 'Earthly', ats: 'https://boards.greenhouse.io/earthly' },
  { name: 'Depot', ats: 'https://boards.greenhouse.io/depot' },
  { name: 'Namespace', ats: 'https://boards.greenhouse.io/namespace' },
  { name: 'Gitpod', ats: 'https://boards.greenhouse.io/gitpod' },
  { name: 'Coder', ats: 'https://boards.greenhouse.io/coder' },
  { name: 'DevPod', ats: 'https://boards.greenhouse.io/devpod' },
  { name: 'Devbox', ats: 'https://boards.greenhouse.io/devbox' },
  { name: 'Jetify', ats: 'https://boards.greenhouse.io/jetify' },
  { name: 'Flox', ats: 'https://boards.greenhouse.io/flox' },
  { name: 'Nix', ats: 'https://boards.greenhouse.io/nix' },
  { name: 'Determinate Systems', ats: 'https://boards.greenhouse.io/determinatesystems' },
  { name: 'Cachix', ats: 'https://boards.greenhouse.io/cachix' },
]

async function main() {
  __slog('Adding remote-first companies...\n')
  let added = 0, existed = 0
  
  for (const c of COMPANIES) {
    const slug = slugify(c.name)
    const existing = await prisma.company.findFirst({ where: { OR: [{ slug }, { name: c.name }] } })
    if (existing) { existed++; continue }
    
    let atsType = 'unknown'
    if (c.ats.includes('greenhouse')) atsType = 'greenhouse'
    else if (c.ats.includes('lever')) atsType = 'lever'
    
    await prisma.company.create({
      data: {
        name: c.name, slug, atsUrl: c.ats,
        logoUrl: 'https://logo.clearbit.com/' + slug.replace(/-/g, '') + '.com',
      }
    })
    added++
  }
  
  const total = await prisma.company.count()
  __slog('Existed:', existed, '| Added:', added, '| Total:', total)
  await prisma.$disconnect()
}

main()
